### ISSUE TITLE
Could you make a branch for python3? 

### ISSUE THREAD

**Issue by becxer** [abisee/cnn-dailymail#13]
Hello, I was impressed with your paper and code.
Can I create a branch for Python 3?
If it's not an excuse, I want to contribute to the conversion. Thanks.

**Comment by JafferWilson** [comment]
If you have Python3 version then you can please pull a request. I am sure the author of the repository will love to include it in. I am also looking for a Python3 version. It will be great if you can contribute.

**Comment by becxer** [comment]
I already converted in [cnn-dailymail](https://github.com/becxer/cnn-dailymail) and [pointer-generator](https://github.com/becxer/pointer-generator) but the branches what I can only pull-request are for master. It need to create other branch for python3 by author.

**Comment by JafferWilson** [comment]
Don't worry the author will verify it and will check what can be done.

**Comment by abisee** [comment]
Hi @becxer @JafferWilson 

I don't plan to maintain a Python 3 version of this code, so I think it makes more sense for @becxer to have administrator privileges over the Python 3 version, not me. So how about I provide a link in the READMEs for both cnn-dailymail and pointer-generator to @becxer's forks?

https://github.com/becxer/cnn-dailymail
https://github.com/becxer/pointer-generator/

**Comment by becxer** [comment]
It's okay to do that. 
Thank you for your reference.

**Comment by abisee** [comment]
OK, done.

**Comment by JafferWilson** [comment]
@becxer I guess this issue needs to be closed....
