### ISSUE TITLE
Could you please provide the processed data for cnn/dailymail?

### ISSUE THREAD

**Issue by taineleau** [abisee/cnn-dailymail#9]
Hi, thanks for your hard work! Could you provide the processed data via google drive or dropbox?

**Comment by JafferWilson** [comment]
You can have it from my repository: https://github.com/JafferWilson/Process-Data-of-CNN-DailyMail
Hope this helps you.

**Comment by taineleau** [comment]
@JafferWilson Thanks for your help! It's so kind of you to share the data.

Would it be more user-friendly if the author could put the link to the ready-to-use data on the README of the project? @abisee

**Comment by JafferWilson** [comment]
@taineleau Sure. If the author like to put links on the READ.ME, it will surely help others.

**Comment by abisee** [comment]
Hi @taineleau,

We would have liked to provide the processed version of the dataset, but were advised not to for legal reasons. This is why we have instead provided code to download and process it.

However, we can provide a link to @JafferWilson's repository. Thanks @JafferWilson!

**Comment by JafferWilson** [comment]
@abisee Thank you for your consideration. It will certainly help people, who do not want to mess with the code and process. :)

**Comment by VikasNS** [comment]
How to get the data in text format?

**Comment by JafferWilson** [comment]
@VikasNS  Please exlpain which data you are talking about? Your query isn't clear.

**Comment by VikasNS** [comment]
I meant, how to convert .story files to .txt files.?
But PyCharm can read .story files so no problem.

**Comment by JafferWilson** [comment]
Then I guess you must close the issue. The issue which you have already raised.

**Comment by samcaetano** [comment]
Hi, I'm trying to use your dataset but it's not so clear for me what file is doing what, I mean: what's the difference between the files inside cnn_stories_tokenized/dm_stories_tokenized and finished_files? And, inside finished_files what is the difference between (train/test/val).bin and their chuncked versions? I'm really trying to understand which files are the correct ones for me to load and work with, but I'm pretty confused.

**Comment by chaine09** [comment]
@JafferWilson  

> IndexError: list index (0) out of range

when running the `.bin` inputs.

It seems that the code used here https://github.com/HsuWanTing/unified-summarization cannot detect the `abstracts` and `article` sections.

**Comment by JafferWilson** [comment]
@chaine09 Please Read the READ.ME of the repository and you can try the example bin that I have created and you will see the reference of the link.
Please let me know if it helped and if not then what is the issues.
